services:
  wakapi:
    build: .
    init: true
    ports:
      - "4001:3000"
    restart: unless-stopped
    environment:
      # PostgreSQL connection
      WAKAPI_DB_TYPE: "postgres"                            # [1]
      WAKAPI_DB_NAME: "wakapi"                              # [1]
      WAKAPI_DB_USER: "wakapi"                              # [1]
      WAKAPI_DB_HOST: "db"                                  # [1]
      WAKAPI_DB_PORT: "5432"                                # [1]
      WAKAPI_DB_PASSWORD: "${WAKAPI_DB_PASSWORD}"           # [2]
      WAKAPI_PASSWORD_SALT: "${WAKAPI_PASSWORD_SALT}"       # [2]
      WAKAPI_MAIL_SMTP_PASS: "${WAKAPI_MAIL_SMTP_PASS}"     # [2]
    networks:
      - dokploy-network

  db:
    image: postgres:17                                    # [1]
    restart: unless-stopped
    environment:
      POSTGRES_USER: "wakapi"                             # [1]
      POSTGRES_PASSWORD: "${WAKAPI_DB_PASSWORD}"          # [2]
      POSTGRES_DB: "wakapi"                               # [1]
    volumes:
      - wakapi-db-data:/var/lib/postgresql/data
    networks:
      - dokploy-network

networks:
  dokploy-network:
    external: true

volumes:
  wakapi-db-data: {}
